const waifus = [

  // 🟢 COMUNES (20)
  { name: "Hinata Hyuga", rarity: "común", img: "https://i.imgur.com/placeholder1.jpg" },
  { name: "Sakura Haruno", rarity: "común", img: "https://i.imgur.com/placeholder2.jpg" },
  { name: "Nami", rarity: "común", img: "https://i.imgur.com/placeholder3.jpg" },
  { name: "Orihime Inoue", rarity: "común", img: "https://i.imgur.com/placeholder4.jpg" },
  { name: "Bulma", rarity: "común", img: "https://i.imgur.com/placeholder5.jpg" },
  { name: "Videl", rarity: "común", img: "https://i.imgur.com/placeholder6.jpg" },
  { name: "Rukia", rarity: "común", img: "https://i.imgur.com/placeholder7.jpg" },
  { name: "Winry Rockbell", rarity: "común", img: "https://i.imgur.com/placeholder8.jpg" },
  { name: "Lucy Heartfilia", rarity: "común", img: "https://i.imgur.com/placeholder9.jpg" },
  { name: "Tsubaki", rarity: "común", img: "https://i.imgur.com/placeholder10.jpg" },
  { name: "Mitsuri (base)", rarity: "común", img: "https://i.imgur.com/placeholder11.jpg" },
  { name: "Ochaco Uraraka", rarity: "común", img: "https://i.imgur.com/placeholder12.jpg" },
  { name: "Kagome Higurashi", rarity: "común", img: "https://i.imgur.com/placeholder13.jpg" },
  { name: "Shinoa Hiragi", rarity: "común", img: "https://i.imgur.com/placeholder14.jpg" },
  { name: "Android 18", rarity: "común", img: "https://i.imgur.com/placeholder15.jpg" },
  { name: "Noelle Silva", rarity: "común", img: "https://i.imgur.com/placeholder16.jpg" },
  { name: "Nejire Hado", rarity: "común", img: "https://i.imgur.com/placeholder17.jpg" },
  { name: "Tamaki Kotatsu", rarity: "común", img: "https://i.imgur.com/placeholder18.jpg" },
  { name: "Kanao Tsuyuri (base)", rarity: "común", img: "https://i.imgur.com/placeholder19.jpg" },
  { name: "Mikasa (joven)", rarity: "común", img: "https://i.imgur.com/placeholder20.jpg" },

  // 🔵 RARAS (20)
  { name: "Rem", rarity: "rara", img: "https://i.imgur.com/placeholder21.jpg" },
  { name: "Ram", rarity: "rara", img: "https://i.imgur.com/placeholder22.jpg" },
  { name: "Asuna", rarity: "rara", img: "https://i.imgur.com/placeholder23.jpg" },
  { name: "Mikasa Ackerman", rarity: "rara", img: "https://i.imgur.com/placeholder24.jpg" },
  { name: "Zero Two", rarity: "rara", img: "https://i.imgur.com/placeholder25.jpg" },
  { name: "Kurisu Makise", rarity: "rara", img: "https://i.imgur.com/placeholder26.jpg" },
  { name: "Tohka Yatogami", rarity: "rara", img: "https://i.imgur.com/placeholder27.jpg" },
  { name: "Yuno Gasai", rarity: "rara", img: "https://i.imgur.com/placeholder28.jpg" },
  { name: "Akame", rarity: "rara", img: "https://i.imgur.com/placeholder29.jpg" },
  { name: "Yor Forger", rarity: "rara", img: "https://i.imgur.com/placeholder30.jpg" },
  { name: "Power", rarity: "rara", img: "https://i.imgur.com/placeholder31.jpg" },
  { name: "Nobara Kugisaki", rarity: "rara", img: "https://i.imgur.com/placeholder32.jpg" },
  { name: "Emilia", rarity: "rara", img: "https://i.imgur.com/placeholder33.jpg" },
  { name: "Himiko Toga", rarity: "rara", img: "https://i.imgur.com/placeholder34.jpg" },
  { name: "Mai Sakurajima", rarity: "rara", img: "https://i.imgur.com/placeholder35.jpg" },
  { name: "Akeno Himejima", rarity: "rara", img: "https://i.imgur.com/placeholder36.jpg" },
  { name: "Rias Gremory (base)", rarity: "rara", img: "https://i.imgur.com/placeholder37.jpg" },
  { name: "Inori Yuzuriha", rarity: "rara", img: "https://i.imgur.com/placeholder38.jpg" },
  { name: "Nezuko (base)", rarity: "rara", img: "https://i.imgur.com/placeholder39.jpg" },
  { name: "Kurumi Tokisaki (base)", rarity: "rara", img: "https://i.imgur.com/placeholder40.jpg" },

  // 🟣 ÉPICAS (20)
  { name: "Rias Demon", rarity: "épica", img: "https://i.imgur.com/placeholder41.jpg" },
  { name: "Esdeath", rarity: "épica", img: "https://i.imgur.com/placeholder42.jpg" },
  { name: "Makima", rarity: "épica", img: "https://i.imgur.com/placeholder43.jpg" },
  { name: "Shinobu Kocho", rarity: "épica", img: "https://i.imgur.com/placeholder44.jpg" },
  { name: "Mitsuri Kanroji", rarity: "épica", img: "https://i.imgur.com/placeholder45.jpg" },
  { name: "Yoruichi Shihouin", rarity: "épica", img: "https://i.imgur.com/placeholder46.jpg" },
  { name: "Saber", rarity: "épica", img: "https://i.imgur.com/placeholder47.jpg" },
  { name: "Nico Robin", rarity: "épica", img: "https://i.imgur.com/placeholder48.jpg" },
  { name: "Boa Hancock", rarity: "épica", img: "https://i.imgur.com/placeholder49.jpg" },
  { name: "Lucy Heartfilia", rarity: "épica", img: "https://i.imgur.com/placeholder50.jpg" },
  { name: "Marin Kitagawa", rarity: "épica", img: "https://i.imgur.com/placeholder51.jpg" },
  { name: "Kaguya Shinomiya", rarity: "épica", img: "https://i.imgur.com/placeholder52.jpg" },
  { name: "Yukino Yukinoshita", rarity: "épica", img: "https://i.imgur.com/placeholder53.jpg" },
  { name: "Momo Yaoyorozu", rarity: "épica", img: "https://i.imgur.com/placeholder54.jpg" },
  { name: "Android 21", rarity: "épica", img: "https://i.imgur.com/placeholder55.jpg" },
  { name: "Tsukuyo", rarity: "épica", img: "https://i.imgur.com/placeholder56.jpg" },
  { name: "C.C.", rarity: "épica", img: "https://i.imgur.com/placeholder57.jpg" },
  { name: "Kurumi (épica)", rarity: "épica", img: "https://i.imgur.com/placeholder58.jpg" },
  { name: "Hinata Byakugan", rarity: "épica", img: "https://i.imgur.com/placeholder59.jpg" },
  { name: "Yoruichi (full)", rarity: "épica", img: "https://i.imgur.com/placeholder60.jpg" },

  // 🟡 LEGENDARIAS (20)
  { name: "Gojo (fan gender)", rarity: "legendaria", img: "https://i.imgur.com/placeholder61.jpg" },
  { name: "Nezuko Diosa", rarity: "legendaria", img: "https://i.imgur.com/placeholder62.jpg" },
  { name: "Makima Control", rarity: "legendaria", img: "https://i.imgur.com/placeholder63.jpg" },
  { name: "Esdeath Emperatriz", rarity: "legendaria", img: "https://i.imgur.com/placeholder64.jpg" },
  { name: "Rias Reina Demonio", rarity: "legendaria", img: "https://i.imgur.com/placeholder65.jpg" },
  { name: "Saber Alter", rarity: "legendaria", img: "https://i.imgur.com/placeholder66.jpg" },
  { name: "Shinobu Diosa", rarity: "legendaria", img: "https://i.imgur.com/placeholder67.jpg" },
  { name: "Mikasa Titan Slayer", rarity: "legendaria", img: "https://i.imgur.com/placeholder68.jpg" },
  { name: "Yoruichi Diosa Gato", rarity: "legendaria", img: "https://i.imgur.com/placeholder69.jpg" },
  { name: "Kurumi Tiempo", rarity: "legendaria", img: "https://i.imgur.com/placeholder70.jpg" },
  { name: "Boa Reina", rarity: "legendaria", img: "https://i.imgur.com/placeholder71.jpg" },
  { name: "Rem Divina", rarity: "legendaria", img: "https://i.imgur.com/placeholder72.jpg" },
  { name: "Zero Two Final", rarity: "legendaria", img: "https://i.imgur.com/placeholder73.jpg" },
  { name: "Emilia Reina Hielo", rarity: "legendaria", img: "https://i.imgur.com/placeholder74.jpg" },
  { name: "Power Demonio", rarity: "legendaria", img: "https://i.imgur.com/placeholder75.jpg" },
  { name: "Yuno Diosa Amor", rarity: "legendaria", img: "https://i.imgur.com/placeholder76.jpg" },
  { name: "Kaguya Otsutsuki", rarity: "legendaria", img: "https://i.imgur.com/placeholder77.jpg" },
  { name: "Sailor Moon Suprema", rarity: "legendaria", img: "https://i.imgur.com/placeholder78.jpg" },
  { name: "Tatsumaki Dios", rarity: "legendaria", img: "https://i.imgur.com/placeholder79.jpg" },
  { name: "Eri Reset", rarity: "legendaria", img: "https://i.imgur.com/placeholder80.jpg" }

]

module.exports = waifus
